### ISSUE TITLE
It doesn't work with Sapphire RX6600XT 8G

### ISSUE THREAD

**Issue by guokai10000** [aluveitie/RadeonSensor#1]
Hi, aluveitie. 
My graphic card is Sapphire RX6600XT 8G which say GPU temperature is 0˚. Could you fix it?
Many thanks.

**Comment by aluveitie** [comment]
Sure, will have a look at it soon.
Thanks for bringing it up.

**Comment by aluveitie** [comment]
@guokai10000 Please try the latest release: https://github.com/aluveitie/RadeonSensor/releases/tag/0.2.0

**Comment by guokai10000** [comment]
The 0.2.0 works!
Thank you for you efforts!

**Comment by aluveitie** [comment]
Thanks for testing :)
