### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by iamyounix** [aluveitie/RadeonSensor#10]
No Catalina support for RadeonGadget

**Comment by aluveitie** [comment]
I think you should be able to compile it on Catalina with only a few tweaks in the project settings

**Comment by nishyp** [comment]
I had this issue also 
![Screen Shot 2022-12-20 at 12 18 14 AM](https://user-images.githubusercontent.com/6903803/208414500-158d480c-58a5-4d6d-add9-d05d6d4b4375.png)

I tried to open the Xcode project after seeing this ticket so I could attempt to tweak the project settings (even though I have no clue what I'm doing haha) but it's made with a newer version than Xcode 12.4 which is the last compatible version for Catalina. So, would you be able to compile a version for us Catalina folk, please? 😅

**Comment by aluveitie** [comment]
I'll see if I can do a build during the holidays

**Comment by aluveitie** [comment]
@nishyp See if that works on Catalina: 
[RadeonGadget.zip](https://github.com/aluveitie/RadeonSensor/files/10323890/RadeonGadget.zip)

**Comment by nishyp** [comment]
Just wanted to confirm this is working, thank you!

![Screen Shot 2023-02-15 at 5 59 39 PM](https://user-images.githubusercontent.com/6903803/218936057-479487cc-f42f-4081-ad06-a6eeab56e403.png)
