### ISSUE TITLE
Compile error: fatal error: 'Headers/kern_efi.hpp' file not found

### ISSUE THREAD

**Issue by DimaVIII** [aluveitie/RadeonSensor#11]
Hello, thank you for this amazing project. 

I have issues compiling the project. Unfortuently I have no much experience with this.

After running xcodebuild I'm getting this fatal error:
```
/Users/macpro/openCore/RadeonSensor-0.3.1/RadeonSensor/RadeonSensor.hpp:20:10: fatal error: 'Headers/kern_efi.hpp' file not found
#include <Headers/kern_efi.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~
```

MacOS 11.6.5
xcode Version 13.2.1 (13C100)

Any advice is much appreciated, or maybe a precompiled version? :)

**Comment by aluveitie** [comment]
To compile the kext you need the debug version of the Lilu.kext placed in the project directory, it contains the necessary headers.

A precompiled version you'll find under https://github.com/aluveitie/RadeonSensor/releases
