### ISSUE TITLE
(SMCRadeonGPU) <compose failure [UUID]>

### ISSUE THREAD

**Issue by Terminalavb** [aluveitie/RadeonSensor#13]
how to fix?

2022-08-15 17:46:33.447641+0200  localhost kernel[0]: (SMCRadeonGPU) <compose failure [UUID]>
2022-08-15 17:46:33.447645+0200  localhost kernel[0]: (SMCRadeonGPU) <compose failure [UUID]>

**Comment by aluveitie** [comment]
did you load the RadeonSensor kext first? SMCRadeonGPU depends on it.

**Comment by Terminalavb** [comment]
Yes. Did you need some logs?

**Comment by Terminalavb** [comment]
Yes.
I had read this in fact the order is correct.  but when I entered propertree it had actually given me a message about SMCRadeon's dependencies, may have removed them.  how can I check them?

Inviato da iPhone
