### ISSUE TITLE
Showing 0°C

### ISSUE THREAD

**Issue by skippydream** [aluveitie/RadeonSensor#15]
Hi! Thank you for your work, I needed that!
Sadly sensor are showing 0°C, in GPU Die, GPU Proximity, and RadeonSensor.app too.

![](https://user-images.githubusercontent.com/36988839/190627872-791d3aa9-4cce-474c-a83c-bad80b5e0ca0.png)

iStats Menu manages to read the temperature here (48°C now), as follows:

![](https://user-images.githubusercontent.com/36988839/190629159-1e44a5e4-28da-4401-a45f-ae823bb98c80.png)

My card is **AMD Sapphire Nitro Radeon R9 380 4 GB** 
  Device ID:	0x6939
  Vendor ID:	0x1002
  Revision ID:	0x00f1

Do you have any ideas? I can't exclude I have broken sensors on my GPU.
Thanks in advance.

Cheers,

Michele 🇮🇹

**Comment by aluveitie** [comment]
Hi,
The device id should be covered by the kext. The actual code is from the RadeonMonitor kext, I have only experience with Vega 2 and higher. Can't really say where possibly the issue is.

As far as I know, Apple stopped reporting the temperature with Vega 2, so you should not need it.
