### ISSUE TITLE
SMCRadeonGPU.kext not working on Mac Pro 5.1 with RX6600 XT

### ISSUE THREAD

**Issue by PeroPenx** [aluveitie/RadeonSensor#16]
While RadeonSensor.kext and RadeonGadget.app work without any problem SMCRadeonGPU is not showing any data in iStats or any other app (Mac Fan Control...).

VirtualSMC is not installed because it is genuine Mac and all other fans data are shown as normal

Installed GPU is XFX Radeon RX6600 XT swift 210 with hardware switch for silent and game mode. It doens't matter which mode is on

**Comment by aluveitie** [comment]
SMCRadeonGPU depends on VirtualSMC to report the temperature.

**Comment by b23prodtm** [comment]
Hi I've got RX 6500 XT and the card isn't supported by RadeonSensor 
DID you 743f

**Comment by nvollmar** [comment]
The 6500 XT isn’t supported by MacOS

**Comment by aluveitie** [comment]
The 6500 XT isn’t supported by MacOS
