### ISSUE TITLE
Mac Pro 5,1 with Opencore and using enterprise card AMD Radeon PRO VII, (Vega 20 GPU)

### ISSUE THREAD

**Issue by jtgil** [aluveitie/RadeonSensor#17]
Hello,

This gadget is great, but it is not working with the AMD Radeon PRO VII, (enterprise card), temperature reporting has not worked either in Stats or iStats app or Macs Fan Control.

Also, when I try to use the included app, it says no radeonsensor found and to download it. I assume this refers to the radeonsensor.kext? 

I have enabled the loading of both the radeonsensor.kext and SMCRadeonGPU.kext in opencore for my machine. So I am not sure what I am missing here.

Maybe this is not worth it since it just to show the temp, but it would be nice to have to be able to control fans according to GPU temp. Is there a chance you could have a look to maybe include this card in the Radeon Sensor gadget? 

Thanks!

**Comment by aluveitie** [comment]
Hi,

SMCRadeonGPU.kext won't work on a real Mac as it relies on VirtualSMC.
Could you give me the device ID of that card?

**Comment by jtgil** [comment]
Hi aluveite,

Thanks for getting back to me! 

Ahh, apologies. Yes, I completely missed this in the other issues opened here and when I was reading on the Mac Pro 5,1 Opencore community regarding this to get newer AMD GPU info.

Here is my device ID card: AMD Radeon Pro VII - 66A1

If I remember correctly, the device ID for the AMD Radeon VII was 66AF... 

So anyway, hopefully it can be included in your code and help whoever has this card and using VirtualSMC.

Thanks a bunch for your time mate!

**Comment by aluveitie** [comment]
Hi @jtgil 
Thanks, I've changed the detection to match all Vega 20 device ids (previously only the VII was matched).

You can try this build: 
[RadeonSensor.kext.zip](https://github.com/aluveitie/RadeonSensor/files/9806741/RadeonSensor.kext.zip)

At least with the RadeonGadget you should see the GPU temperature.
