### ISSUE TITLE
All sensors are supported on masOS 13.0

### ISSUE THREAD

**Issue by wuuuluojun** [aluveitie/RadeonSensor#19]
BRO, i was update to 13.0 today. i found that all sensors are supported by Apple Inc. 
<img width="280" alt="image" src="https://user-images.githubusercontent.com/32636096/198682537-9de919c2-0eb3-4ddd-81cf-333711de8612.png">
thank you for your contribution.

**Comment by taarkov** [comment]
How did you work this kext on 13.0 while i can't do that on 13.0.1? I use 6800 and when i enable both these kext it just reboots at start of verbose, there is no problem on disabled.

**Comment by aluveitie** [comment]
I don't daily drive my hackintosh myself anymore. But I recently upgraded it to Ventura and it worked so far, though I'm not using the SMCRadeonGPU kext.

**Comment by taarkov** [comment]
Thanks for the info, gonna try without SMC.

**Comment by taarkov** [comment]
Yeah it works without SMC plugin.
![image](https://user-images.githubusercontent.com/66971137/205847929-08e17a80-ac93-46c5-9e43-2817dc7faf7d.png)
