### ISSUE TITLE
Is there a way to support iStat Menu?

### ISSUE THREAD

**Issue by kingo132** [aluveitie/RadeonSensor#2]
Hi, aluveitie, thank you for your great work. I'm wondering if there is any way to support iStat Menu, is this possible?
Thank you!

**Comment by aluveitie** [comment]
Not really.
There is no SMC key for the GPU temperature. FakeSMC adds custom ones which are supported by Apps like iStats. For that use case you’d have to use the original FakeSMC+RadeonMonitor.

**Comment by huijiewei** [comment]
maybe can use VirtualSMC API to register data to SMC

https://github.com/acidanthera/VirtualSMC/blob/master/Docs/SensorInfo.md

**Comment by aluveitie** [comment]
@huijiewei Since Apple does not have a key for it, VirtualSM does not have one too.

One of the core principles of Acidanthera is to stay as close to an original Mac as possible. 

And the sole reason for this kext is to provide the GPU temperature in some way for people using VirtualSMC.

**Comment by kingo132** [comment]
Do you mean we need to develop a VirtualSMC plugin like SMCRadeonGPU to achieve this? Like these plugins
![image](https://user-images.githubusercontent.com/46492291/139802548-9e55d1a3-93cb-4544-93dd-b22b07131774.png)

**Comment by aluveitie** [comment]
I already looked into it but had to dismiss it.
There is no SMC key for the GPU temperature to be reported to. VirtualSMC does not have one since original Macs don't have one.

FakeSMC invented its own SMC keys for such things, and iStats adapted to also support FakeSMC's keys. As long as VirtualSMC, or Apple for that matter, do not add one I can't do anything in that regard.

(SMCProcessor, like SMCAMDProcessor, do just that, report the temperature for the CPU temperature key which is available on any Mac and therefore on VirtualSMC)

**Comment by kingo132** [comment]
I see, thanks, and my final question is, could we let this SMCRadeonGPU plugin simulate that SMC key that FakeSMC does? So iStats will recognize and show the GPU temperature?

**Comment by aluveitie** [comment]
I'm not aware that VirtualSMC provides such a functionality.

**Comment by kingo132** [comment]
I see, thank you for your detailed explanation.

**Comment by huijiewei** [comment]
I found TG0P key in

https://github.com/acidanthera/VirtualSMC/blob/master/Sensors/SMCDellSensors/SMCDellSensors.hpp

https://github.com/acidanthera/VirtualSMC/blob/master/Sensors/SMCDellSensors/SMCDellSensors.cpp

**Comment by aluveitie** [comment]
@huijiewei Thanks, I must have overlooked that last time, I only found the iGPU temp key... I'll try to resurrect my SMCRadeonSensor again with that key. Maybe it will work this time around 👍

**Comment by aluveitie** [comment]
I've prepared a SMCRadeonGPU kext that exports the GPU temperature as `TG0P` and `TG0p`:
[RadeonSensor.zip](https://github.com/aluveitie/RadeonSensor/files/7467757/RadeonSensor.zip)

**Comment by kingo132** [comment]
hi, aluveitie, thank you for your work, I tested this SMCRadeonGPU, it is successfully loaded but iStats menu can not read the GPU temperature. Here is the screenshot.
![image](https://user-images.githubusercontent.com/46492291/140074534-877c54ef-700a-463c-a97a-6f827f9df39b.png)
![image](https://user-images.githubusercontent.com/46492291/140074612-4afb2362-9112-44e9-99d9-523688cdedb0.png)

**Comment by aluveitie** [comment]
<img width="176" alt="Screenshot 2021-11-03 at 16 26 51" src="https://user-images.githubusercontent.com/61966108/140090918-bd9826ed-b365-4895-9531-748577b911bd.png">

Weird, the keys end up in the wrong order... ???

**Comment by huijiewei** [comment]
maybe you can try HWMonitorSMC2?

**Comment by aluveitie** [comment]
Can you test with this:
[SMCRadeonGPU.kext.zip](https://github.com/aluveitie/RadeonSensor/files/7468984/SMCRadeonGPU.kext.zip)

**Comment by aluveitie** [comment]
with the smc command line tool I can read out the keys:
```
  TG0P  [87ps]  (bytes 25 00)
  TG0p  [87ps]  (bytes 25 00)
```

And 0x25 is correct, 37 C. Don't understand why HWMonitorSMC2 still only shows 0.

**Comment by horus1963** [comment]
On my system, both iStats Menus and HWMonitorSMC2 read 0 but strangely, Sensei manages to display the correct temperature only on its dashboard but not on its detail tab.

![image](https://user-images.githubusercontent.com/11258233/140205526-a85bc1d0-7b03-4105-9d16-85dc90ec3262.png)

**Comment by horus1963** [comment]
Also iStats and HWMonitorSMC2 seem now to think I have 2 GPUs.

**Comment by huijiewei** [comment]
I use VirtualSMC-1.2.7-RELEASE Tools smcread get info, it look type is reverse

```
➜  Tools ./smcread -s
macOS 12.0.1 (21A559)
Public keys (113):
[#KEY] type [ui32] 75693332 len [ 4] attr [80] -> 00000071
[$Adr] type [ui32] 75693332 len [ 4] attr [80] -> 00000300
[$Num] type [ui8 ] 75693820 len [ 1] attr [D0] -> 01
[BATP] type [flag] 666C6167 len [ 1] attr [80] -> 00
[BEMB] type [flag] 666C6167 len [ 1] attr [80] -> 00
[CLKH] type [{clh] 7B636C68 len [ 8] attr [D0] -> 0000708000011940
[CLKT] type [ui32] 75693332 len [ 4] attr [D0] -> 000002E5
[CLWK] type [ui16] 75693136 len [ 2] attr [D0] -> AAA2
[CRCA] type [ui32] 75693332 len [ 4] attr [80] -> 6E76E435
[CRCB] type [ui32] 75693332 len [ 4] attr [80] -> 45FA9DCB
[CRCC] type [ui32] 75693332 len [ 4] attr [80] -> A82D3871
[CRCF] type [ui32] 75693332 len [ 4] attr [90] -> 3B6763ED
[CRCK] type [ui32] 75693332 len [ 4] attr [90] -> 00000000
[CRCR] type [ui32] 75693332 len [ 4] attr [80] -> 0EF3989A
[CRCU] type [ui32] 75693332 len [ 4] attr [80] -> 49266B5C
[CRCa] type [ui32] 75693332 len [ 4] attr [90] -> 6E76E435
[CRCb] type [ui32] 75693332 len [ 4] attr [90] -> 45FA9DCB
[CRCc] type [ui32] 75693332 len [ 4] attr [90] -> A82D3871
[CRCr] type [ui32] 75693332 len [ 4] attr [90] -> 0EF3989A
[CRCu] type [ui32] 75693332 len [ 4] attr [90] -> 49266B5C
[DPLM] type [{lim] 7B6C696D len [ 5] attr [51] -> NOT READABLE, code 85
[DUSR] type [ui8 ] 75693820 len [ 1] attr [40] -> NOT READABLE, code 85
[EFBM] type [ui8 ] 75693820 len [ 1] attr [C0] -> 00
[EFBP] type [ui8 ] 75693820 len [ 1] attr [C0] -> 00
Unable to read smc value E00002C1
[EFBS] type [ui8 ] 75693820 len [ 1] attr [90] -> NOT READABLE, code FF
[EPCI] type [ui32] 75693332 len [ 4] attr [80] -> 0810F000
[EVCT] type [hex_] 6865785F len [ 2] attr [D0] -> 0000
[EVHF] type [ch8*] 6368382A len [28] attr [90] -> 00000000000000000000000000000000000000000000000000000000
[EVRD] type [ch8*] 6368382A len [32] attr [90] -> 0000000000000000000000000000000000000000000000000000000000000000
[FAC0] type [ui8 ] 75693820 len [ 1] attr [C0] -> 00
[FNum] type [ui8 ] 75693820 len [ 1] attr [80] -> 06
[HBKP] type [ch8*] 6368382A len [32] attr [C0] -> 0000000000000000000000000000000000000000000000000000000000000000
[LDKN] type [ui8 ] 75693820 len [ 1] attr [80] -> 02
[LDLG] type [ch8*] 6368382A len [ 1] attr [50] -> NOT READABLE, code 85
[LDSP] type [flag] 666C6167 len [ 1] attr [40] -> NOT READABLE, code 85
[LsNM] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[MSDW] type [flag] 666C6167 len [ 1] attr [50] -> NOT READABLE, code 85
[MSFW] type [flag] 666C6167 len [ 1] attr [C0] -> 00
[MSPC] type [ui8 ] 75693820 len [ 1] attr [D0] -> 19
[MSPP] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[MSPR] type [ui8 ] 75693820 len [ 2] attr [80] -> 0001
[MSPS] type [hex_] 6865785F len [ 2] attr [80] -> 0004
[MSQC] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[MSSD] type [si8 ] 73693820 len [ 1] attr [D0] -> 05
[MSSP] type [si8 ] 73693820 len [ 1] attr [C0] -> 05
[MSSW] type [flag] 666C6167 len [ 1] attr [C0] -> 00
[MSTc] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[MSTe] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[MSTf] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[MSTi] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[MSTj] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[MSTm] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[MSWr] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
[NATJ] type [ui8 ] 75693820 len [ 1] attr [C0] -> 00
[NATi] type [ui16] 75693136 len [ 2] attr [C0] -> 0000
[NTOK] type [ui8 ] 75693820 len [ 1] attr [50] -> NOT READABLE, code 85
[OSWD] type [ui16] 75693136 len [ 2] attr [C0] -> 001A
[RBr ] type [ch8*] 6368382A len [ 8] attr [80] -> 6A3133385F390000
[REV ] type [{rev] 7B726576 len [ 6] attr [90] -> 02460F000012
[RGEN] type [ui8 ] 75693820 len [ 1] attr [80] -> 02
[RMAC] type [ch8*] 6368382A len [ 6] attr [C4] -> 7085C2A717BA
[RMSN] type [ch8*] 6368382A len [17] attr [C4] -> 43303239353231303251584C4E56394138
[RMde] type [char] 63686172 len [ 1] attr [80] -> 41
[RPlt] type [ch8*] 6368382A len [ 8] attr [80] -> 6A31333800000000
[RSSN] type [ch8*] 6368382A len [16] attr [C4] -> 4330325A573037464A56335100000000
[RVBF] type [{rev] 7B726576 len [ 6] attr [90] -> 02460F000012
[RVCR] type [{rev] 7B726576 len [ 6] attr [90] -> FFFFFFFFFFFF
[RVUF] type [{rev] 7B726576 len [ 6] attr [90] -> 02460F000012
[WKTP] type [ui8 ] 75693820 len [ 1] attr [D0] -> 00
[PC0C] type [sp96] 73703936 len [ 2] attr [80] -> 032B
[PC0G] type [sp96] 73703936 len [ 2] attr [80] -> 0000
[PC0R] type [sp96] 73703936 len [ 2] attr [80] -> 032B
[PC3C] type [flt ] 666C7420 len [ 4] attr [80] -> DB20843F
[PCAM] type [flt ] 666C7420 len [ 4] attr [80] -> D2C44A41
[PCEC] type [flt ] 666C7420 len [ 4] attr [80] -> DB20843F
[PCGC] type [flt ] 666C7420 len [ 4] attr [80] -> 00000000
[PCGM] type [flt ] 666C7420 len [ 4] attr [80] -> 00000000
[PCPC] type [sp96] 73703936 len [ 2] attr [80] -> 032B
[PCPG] type [sp96] 73703936 len [ 2] attr [80] -> 0000
[PCPR] type [sp96] 73703936 len [ 2] attr [80] -> 037F
[PCPT] type [sp96] 73703936 len [ 2] attr [80] -> 037F
[PCTR] type [sp96] 73703936 len [ 2] attr [80] -> 037F
[TC0C] type [sp78] 73703738 len [ 2] attr [80] -> 1E00
[TC0D] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[TC0E] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[TC0F] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[TC0G] type [sp78] 73703738 len [ 2] attr [80] -> 0000
[TC0H] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[TC0J] type [sp78] 73703738 len [ 2] attr [80] -> 0000
[TC0P] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[TC0c] type [sp78] 73703738 len [ 2] attr [80] -> 1E00
[TC0p] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[TC1C] type [sp78] 73703738 len [ 2] attr [80] -> 1D00
[TC1c] type [sp78] 73703738 len [ 2] attr [80] -> 1D00
[TC2C] type [sp78] 73703738 len [ 2] attr [80] -> 1F00
[TC2c] type [sp78] 73703738 len [ 2] attr [80] -> 1F00
[TC3C] type [sp78] 73703738 len [ 2] attr [80] -> 1F00
[TC3c] type [sp78] 73703738 len [ 2] attr [80] -> 1F00
[TC4C] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[TC4c] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[TC5C] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[TC5c] type [sp78] 73703738 len [ 2] attr [80] -> 2000
[VC0C] type [sp3c] 73703363 len [ 2] attr [80] -> 0B70
[TG0P] type [87ps] 38377073 len [ 2] attr [80] -> 3000
[TG0p] type [87ps] 38377073 len [ 2] attr [80] -> 3000
[TG0D] type [?] 00000000 len [ 0] attr [00] -> NOT READABLE, code 89
[TG0d] type [?] 00000000 len [ 0] attr [00] -> NOT READABLE, code 89
[F0Ac] type [fpe2] 66706532 len [ 2] attr [80] -> 0B5C
[F1Ac] type [fpe2] 66706532 len [ 2] attr [80] -> 07BC
[F2Ac] type [fpe2] 66706532 len [ 2] attr [80] -> 0000
[F3Ac] type [fpe2] 66706532 len [ 2] attr [80] -> 0000
[F4Ac] type [fpe2] 66706532 len [ 2] attr [80] -> 0000
[F5Ac] type [fpe2] 66706532 len [ 2] attr [80] -> 0000

Hidden keys (?):
[____] type [flag] 666C6167 len [ 1] attr [80] -> 01
[OSK0] type [ch8*] 6368382A len [32] attr [90] -> 6F757268617264776F726B62797468657365776F72647367756172646564706C
[OSK1] type [ch8*] 6368382A len [32] attr [90] -> 65617365646F6E74737465616C2863294170706C65436F6D7075746572496E63
[KPPW] type [ch8*] 6368382A len [32] attr [50] -> NOT READABLE
[KPST] type [ui8 ] 75693820 len [ 1] attr [80] -> 00
```

**Comment by aluveitie** [comment]
@huijiewei Thanks for the hint, that might be an issue. For some reason `EFIAPI` is defined (don't know from which import yet...) which reverses some stuff... I'll keep digging, getting closer :)

**Comment by aluveitie** [comment]
Release 0.3.0 now correctly provides the GPU temperature for monitoring tools to read.

Thanks for the testing and hints to get me in the right direction!

**Comment by horus1963** [comment]
Sorry. Still doesn't work for me. As you can see, HWMonitorSMC2 things I have two GPUs and reports the temperature for the second unreal GPU (GPU 0) and not for my 6800 XT. iStats Menus still shows nothing. 
<img width="1030" alt="Screen Shot 2021-11-04 at 12 29 10 PM" src="https://user-images.githubusercontent.com/11258233/140380136-cd0b091c-41cc-4763-8417-72f940574cc2.png">
<img width="1050" alt="Screen Shot 2021-11-04 at 12 29 37 PM" src="https://user-images.githubusercontent.com/11258233/140380138-f8c11eae-1aeb-4c9f-bd40-de5e1405ae76.png">

**Comment by aluveitie** [comment]
Which SMBIOS are you using?

**Comment by horus1963** [comment]
Macpro7,1 and still on 11.6.1

**Comment by horus1963** [comment]
Maybe iStats is expecting something like TG1D? (Die instead of Proximity for GPU 1?)

**Comment by aluveitie** [comment]
I was also testing with HWMonitorSMC2 and MacPro7,1 and a 6900 XT. Looked fine, no idea what would have gone wrong here…

**Comment by horus1963** [comment]
Can you please try adding TG0d as well as p for me to test? Since for some reason my iStats Menu is looking for die temperature?

**Comment by aluveitie** [comment]
@horus1963 this version exports TG0D and TG0P: [SMCRadeonGPU.kext.zip](https://github.com/aluveitie/RadeonSensor/files/7480918/SMCRadeonGPU.kext.zip)

**Comment by kingo132** [comment]
I think it does not work for me too ... iStats Menu still can't read the GPU temp.

![image](https://user-images.githubusercontent.com/46492291/140467856-2b366707-7d3a-4330-a663-e6008ddac701.png)

The smc key seems successfully set
![image](https://user-images.githubusercontent.com/46492291/140468028-0b44725e-4278-4033-b5e2-47c0833a429a.png)

**Comment by aluveitie** [comment]
@kingo132 Which SMBIOS are you using? iStats is only showing values known by that specific SMBIOS.

**Comment by kingo132** [comment]
> @kingo132 Which SMBIOS are you using? iStats is only showing values known by that specific SMBIOS.

I'm using iMac 20,2, here is the original SMC key info I dumped from the real iMac 20,2.
[SMC-keys.txt](https://github.com/aluveitie/RadeonSensor/files/7481071/SMC-keys.txt)

As you can see, it has TG0P, TG0p, TG0D, TG0d.

And after I used your last SMCRadeonGPU.kext.zip which supports TG0D, the temperature comes out, but not in GPU proximity, it's in the GPU line.

![image](https://user-images.githubusercontent.com/46492291/140468833-893ad6c3-d68e-401e-bf0b-5f07aa93528c.png)

**Comment by aluveitie** [comment]
This would provide TG0p/TG0d: [SMCRadeonGPU.kext.zip](https://github.com/aluveitie/RadeonSensor/files/7481103/SMCRadeonGPU.kext.zip)

**Comment by kingo132** [comment]
> This would provide TG0p/TG0d: [SMCRadeonGPU.kext.zip](https://github.com/aluveitie/RadeonSensor/files/7481103/SMCRadeonGPU.kext.zip)

This kext moves the temperature from GPU to GPU Proximity in my machine, really interesting ...

![image](https://user-images.githubusercontent.com/46492291/140469532-936cdabb-1620-4b8b-adcc-978ccff21fbd.png)

**Comment by aluveitie** [comment]
In your case I'd assume TG0D/TG0p would show the GPU temperature in both

**Comment by kingo132** [comment]
> In your case I'd assume TG0D/TG0p would show the GPU temperature in both

That's interesting, could you export all of them so we all could read the temperature?

**Comment by aluveitie** [comment]
So far I'd see TG0D/TG0P as a good combo, HWMonitorSMC2 only lists Proximity (which is not what this temperature is). iStats lists the more correct Die Temperature.

**Comment by aluveitie** [comment]
This does export TG0D/d and TG0P/p:
[SMCRadeonGPU.kext.zip](https://github.com/aluveitie/RadeonSensor/files/7483903/SMCRadeonGPU.kext.zip)

Let me now if that improves things for you

**Comment by aluveitie** [comment]
talkinghead from the Hackintosh Forum also did some investigation and had some interesting findings:
iStats is looking for TG0p, and is ignoring TG0P
Mac FanControl is looking for both TG0P/p and would also read TG0d.

Also the keys have to be registered in alphabetical order, if TG0p is registered before TG0d, TG0d will be empty.
I'm going to test with TG0p/TG0d, that seems the best combination so far.

**Comment by aluveitie** [comment]
Release 0.3.1 exports TG0D/d and TG0P/p, hopefully iStats picks up on that :)
