### ISSUE TITLE
Can it support iStat Menu & Sensei within Ventura?

### ISSUE THREAD

**Issue by bangkuo** [aluveitie/RadeonSensor#20]
Hi, thanks for the cool tool.

Just wondering can it be supported for iStat Menu & Sensei in Ventura?

My graphic is RX590, RadeonGadget App works in Ventura, I can see temperature from menu, but cannot display GPU temperature both from Sensei and iStat Menu, Lilu and VirtualSMC has been loaded correctly but just no show GPU temperature.

Any ideas? Thank you.

**Comment by aluveitie** [comment]
iStat an the like depend on the SMBIOS used, might be related to #14

**Comment by aluveitie** [comment]
I've added the TGDD key as discussed in #14, can you try this version: 
[SMCRadeonGPU.kext.zip](https://github.com/aluveitie/RadeonSensor/files/10379327/SMCRadeonGPU.kext.zip)

**Comment by bangkuo** [comment]
Tried but not lucky, same result not showing GPU temperature, thank you sir.
