### ISSUE TITLE
After updating to 0.3.2, 6800 XT's GPU die temp cannot be detected.

### ISSUE THREAD

**Issue by Purgepyro** [aluveitie/RadeonSensor#21]
<img width="1214" alt="Screen Shot 2023-02-15 at 21 27 15 PM" src="https://user-images.githubusercontent.com/98635189/219040250-6e1ef106-357d-4f47-a5f4-015a41f95540.png">

**Comment by aluveitie** [comment]
Is it detected by the RadeonGadget?

**Comment by Purgepyro** [comment]
<img width="1214" alt="Screen Shot 2023-02-15 at 21 31 17 PM" src="https://user-images.githubusercontent.com/98635189/219041183-e89f360e-3697-4103-a1f6-6d686471efb4.png">
That is when 3.1 is loaded.

**Comment by Purgepyro** [comment]
> Is it detected by the RadeonGadget?

I will try now.

**Comment by aluveitie** [comment]
And check whether the RadeonSensor/SMCRadeonGPU kexts have been loaded with 
```
kextstat | grep Radeon
```

**Comment by Purgepyro** [comment]
Radeon Gadget can both get GPU temp in version 0.3.1 and 0.3.2.
This is what the terminal shows.
<img width="697" alt="Screen Shot 2023-02-15 at 21 36 11 PM" src="https://user-images.githubusercontent.com/98635189/219042310-d3a63df2-fec1-4ac4-bf05-a1b5a868b91e.png">
The kext seems to load nicely.

**Comment by JackWu2006** [comment]
> Radeon Gadget can both get GPU temp in the version 3.1 and 3.2. This is what the terminal shows. <img alt="Screen Shot 2023-02-15 at 21 36 11 PM" width="697" src="https://user-images.githubusercontent.com/98635189/219042310-d3a63df2-fec1-4ac4-bf05-a1b5a868b91e.png">

**Comment by aluveitie** [comment]
Hm, then the added TGDD key might confuse the monitoring App you're using

**Comment by Purgepyro** [comment]
So what's the resolution?

**Comment by aluveitie** [comment]
Use 0.3.1 for the time being, as 0.3.2 doesn't bring anything new for you

**Comment by Purgepyro** [comment]
Thank you!

**Comment by aluveitie** [comment]
I don't know if I can do anything besides removing the key again. It's kind of a whack-a-mole game with those monitoring apps.

**Comment by Purgepyro** [comment]
By the way, temp can be seen in Dashboard, but in cooling it just disappears.
<img width="423" alt="Screen Shot 2023-02-15 at 21 43 28 PM" src="https://user-images.githubusercontent.com/98635189/219043931-28b3d04b-6efe-4a34-b3c3-9869182d8917.png">

**Comment by aluveitie** [comment]
Weird, what app is that?

**Comment by Purgepyro** [comment]
Sensei, the lastest version.

**Comment by Purgepyro** [comment]
Something happy is that iStat can show GPU temp (I have just tried)!

**Comment by aluveitie** [comment]
I did add TGDD to improve things for iStat, but it apparently made it worse for Sensei.

**Comment by Purgepyro** [comment]
Go for it, I hope you can solve this problem easily! (It is also ok to leave it! Good work!)

**Comment by i0ntempest** [comment]
I'm using iStat Menus 6.70 (1216) and the temp of my 6800xt also disappeared in 0.3.2.

**Comment by aluveitie** [comment]
Thanks for the feedback, I put a note in the release notes and marked it as pre-release. I’ll look into it and probably revert the change once I’m back next week.

**Comment by Purgepyro** [comment]
Maybe the previous TGDD even works better?

**Comment by aluveitie** [comment]
I've reverted back and removed TGDD again in the 0.3.3 release.

**Comment by Purgepyro** [comment]
It now works nicely!
<img width="1214" alt="Screen Shot 2023-03-03 at 18 17 20 PM" src="https://user-images.githubusercontent.com/98635189/222694758-25c42e63-bbc4-4316-b705-61eed2e6e4d8.png">
