### ISSUE TITLE
After updating to 0.3.2, 6600 XT's GPU temp cannot be detected

### ISSUE THREAD

**Issue by perez987** [aluveitie/RadeonSensor#22]
[After updating to 0.3.2, 6800 XT's GPU die temp cannot be detected - Issue #21](https://github.com/aluveitie/RadeonSensor/issues/21)

Same for me with 2 RX 6600 XT in 2 identical Hacks (Z390 + i9-9900) but it's iStat Menus where I've lost the GPU temp.
Previous version working fine.
RadeonGadget.app works fine in both versions.
Kexts seems to be loaded with `kextstat | grep Radeon`.
Anyway, thanks for your work.

**Comment by CrazyCreator13** [comment]
the same here

**Comment by i0ntempest** [comment]
Same here

**Comment by Purgepyro** [comment]
You can go to see the issue #21.

**Comment by perez987** [comment]
Closing issue since @aluveitie already knows the problem
