### ISSUE TITLE
VirtualSMC v1.2.8 Unable to read GPU temperature

### ISSUE THREAD

**Issue by huiyi9420** [aluveitie/RadeonSensor#7]
The temperature of the GPU with the latest RadeonSensor 0.31 and SNCRadebGPU version 0.31 with VirtualSMC v1.2.8 can't be read.

**Comment by aluveitie** [comment]
I will have to check if there has something changed in lastest VirtualSMC as I don’t use the SMCRadeonGPU myself.

**Comment by aluveitie** [comment]
I've rebuilt against the latest VirtualSMC version, there doesn't seem to have been a breaking change.

Are you loading the kets in the right order? VirtualSMC, RadeonSensor and last SMCRadeonGPU?

**Comment by dredhorse** [comment]
Hi, just had the same issue. Perhaps you should update the readme with some simple steps on how to use RadeonSensor correctly.

Thanks for the tool 😀
