### ISSUE TITLE
No Kexts in 0.3.1

### ISSUE THREAD

**Issue by screenpunch** [aluveitie/RadeonSensor#9]
The release zip
https://github.com/aluveitie/RadeonSensor/releases/download/0.3.1/RadeonSensor-0.3.1.zip

Doesn't contain any kexts, what is the latest build? Should I be using kexts in 0.3.0?

**Comment by aluveitie** [comment]
I've just re-downloaded the zip, the kexts are there

**Comment by screenpunch** [comment]
Thanks, IDK what I was doing wrong - I see them now.

Thanks for this project, you should contact the OpenCore dev so that they can include a link to these on their site.
